version: "3"
services:
  redis:
    image: redis:alpine3.18
  sessionms:
    image: efner/session-microservice:1.0
    environment:
      - REDIS_ADDRESS=redis:6379
    ports:
      - "9090:9090"
    depends_on:
      - redis
    entrypoint: "/app/session-microservice"
